name: Guide deploy

on:
  # trigger deployment on every push to main branch
  push:
    branches: [ main ]
  # trigger deployment manually
  workflow_dispatch:

jobs:
  guide:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # choose node.js version to use
          node-version: '16'

      # install dependencies
      - name: Install dependencies
        run: npm install

      # run build script
      - name: Build VuePress site
        run: npm run build

      # please check out the docs of the workflow for more details
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vuepress/dist
